<?php

return [
    "reminder_treatment_sms_txt" => "Hej :name ,\r\n\r\nTak fordi du gør brug af os. Denne sms er for at minde dig om din booking.\r\n\r\nBehandling: :treatment \r\nBehandlings Dato: :date \r\nBehandlings Tidspunkt: :time \r\nSms fra: :link\r\n\r\nDu kan ikke svare på denne SMS.",
    "reminder_event_sms_txt" => "Hej, :name ,\r\n\r\nTak fordi du gør brug af os. Denne sms er for at minde dig om din booking.\r\n\r\nBegivenhedens Navn:<b> :event \r\nBegivenhedens Dato: :date \r\nBegivenhedens Tidspunkt: :time \r\nDin Booking Status: :status \r\nSms fra: :link\r\n\r\nDu kan ikke svare på denne SMS.",
    "clips_used_txt" => "Hej :name,\r\n\r\nTak fordi du gør brug af os. Denne sms er for at informere dig om at der er blevet brug et klip fra dit klippekort :used clips. Yderligere detajler findes herunder.\r\n\r\nKort Titel: :title .\r\nUdløbs Dato: :expiry .\r\nKlip på Kort: :clips .\r\nKort til brug af: :for.\r\n\r\nDu kan ikke svare på denne SMS.",
    "treatment_bookin_restore_txt" => "Hej :name ,\r\n\r\nTak fordi du gør brug af os. Denne besked er for at meddele dig din bookning er blevet gendannet. Læs yderligere om din bookning herunder.\r\n\r\nBehandling: :treatment .\r\nBehanlings Dato: :date .\r\nBehandlings Tidspunkt: :time .\r\nSms fra: :link\r\n\r\nDu kan ikke svare på denne SMS.",
    "treatment_booking_txt" => "Hej :name,\r\n\r\nTak fordi du gør brug af os. Find detaljer for din bookning herunder.\r\n\r\nBehandling: :treatment\r\nBehandlings Dato: :date\r\nBehandlings Tidspunkt: :time \r\nSms fra: :link\r\n\r\nDu kan ikke svare på denne SMS.",
    "treatment_booking_cancel_txt" =>  "Hej :name,\r\n\r\nTak fordi du gør brug af os. Denne besked er for at informere dig om din bookning er blevet afbestilt. Læs yderligere herunder.\r\n\r\nBehandling: :treatment.\r\nBehandlings Dato: :date.\r\nBehandlings tidspunkt: :time.\r\nSms fra: :link\r\n\r\nDu kan ikke svare på denne SMS.",
    "card_clip_purchased_txt" => "Hej :name,\r\n\r\nTak fordi du gør brug af os. Denne besked er for at informere dig om at din behandling er blevet betalt med :purchase klip. Læs yderligere herunder.\r\n\r\nKort Titel: :title .\r\nUdløbs Dato: :date .\r\nKlip på Kort: :clips .\r\nKort til brug af: :for .\r\n\r\nDu kan ikke svare på denne SMS.",
    "clips_restore_txt" => "Hej :name ,\r\n\r\nTak fordi du gør brug af os. Denne email er for at informere dig om dit klippekort :amount has been restored. Læs yderligere herunder.\r\n\r\nKort Titel: <b> :title \r\nUdløbs Dato: :expiry \r\nClips in Card: :clips \r\nCard use for: :for \r\n\r\nDu kan ikke svare på denne SMS.",
    "event_book_txt" => "Hej :name,\r\n\r\nTak fordi du gør brug af os. Læs yderligere om din bookning herunder.\r\n\r\nBegivenhed: :ename .\r\nBegivenheds Dato: :date .\r\nBegivenheds Tidspunkt: :time .\r\nBooking Status: :status \r\n :guest \r\n\r\nDu kan ikke svare på denne SMS.",
    "event_booking_cancel_txt" => "Hej :name,\r\n\r\nTak fordi du gør brug af os. Denne besked er for at informere dig om din bookning til denne begivenhed er blevet slettet. Læs yderligere om din bookning herunder.\r\n\r\nBegivenhed: :ename .\r\nBegivenheds Dato: :date .\r\nBegivenheds Tidspunkt: :time .\r\n :status r\n\r\nDu kan ikke svare på denne SMS.",
    "mobile_pay_txt" => "Hej :name ,\r\n\r\nTak fordi du gør brug af os. Klik på linket nedenfor for betaling på mobilePay. \r\n\r\n :link ",

];